name: protips
description: Divulgação de prognóstico esportivos.

version: 1.1.53+53

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  animations: ^1.1.2
  device_info: ^1.0.0
  dynamic_theme: ^1.0.1
  dio: any
  firebase_analytics: ^6.2.0
  firebase_core: ^0.5.2
  firebase_auth: ^0.18.3
  firebase_storage: ^5.0.1
  firebase_database: ^4.3.0
  firebase_messaging: ^7.0.3
  #  flutter_google_pay: ^0.1.4
  flutter_local_notifications: ^3.0.1+5
  google_api_availability: ^2.0.4
  google_sign_in: ^4.1.1
  image_crop: ^0.3.2
  image_picker: ^0.6.7+3
  #  in_app_purchase: ^0.3.4+3
  intl: ^0.16.1
  package_info: ^0.4.0+16
  path_provider: ^1.6.11
  random_string: ^2.1.0
#  rxdart: ^0.24.1 # <- Subject
  shared_preferences: ^0.5.12+4
  show_more_text_popup: ^0.2.0
  url_launcher: ^5.7.10

  flutter:
    sdk: flutter
#  flutter_localizations:
#    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_launcher_icons: ^0.7.5
  flutter_launcher_name: ^0.0.1
  flutter_test:
    sdk: flutter

flutter_icons:
  adaptive_icon_background: '#044476'
  adaptive_icon_foreground: "assets/icons/ic_launcher_adaptive.png"
  image_path_android: "assets/icons/ic_launcher.png"
  image_path_ios: "assets/icons/ic_launcher_ios.png"
  android: true
  ios: true

flutter_launcher_name:
  name: 'ProTips'

flutter:

  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: Century
      fonts:
        - asset: assets/fonts/century_gothic.ttf
    - family:  MyIcons
      fonts:
        - asset: assets/fonts/MyIcons.ttf
